name: APK Build

on:
  pull_request: { }
  push:
    branches: [ main, develop ]

permissions: {}

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g" -Dkotlin.daemon.jvm.options="-Xmx2560m" -Dkotlin.incremental=false
  CI_GRADLE_ARG_PROPERTIES: --stacktrace -PpreDexEnable=false --max-workers 2 --no-daemon

jobs:
  debug:
    name: Build debug APKs (Fdroid)
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref == 'refs/heads/develop' && format('integration-tests-develop-fdroid-{0}', github.sha) || format('build-debug-fdroid-{0}', github.ref) }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false
      - name: Use JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Configure gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
      - name: Assemble Fdroid debug apk
        run: ./gradlew assembleFdroidDebug $CI_GRADLE_ARG_PROPERTIES
      - name: Upload Fdroid debug APKs
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: vector-Fdroid-debug
          path: |
            vector-app/build/outputs/apk/fdroid/debug/*.apk
